### SpliceAid-F

In [1]:
import pandas as pd

path = "/Users/zihengdai/Desktop/Thesis/data/SpliceAid_F/f.1760348830.899.txt"

df = pd.read_csv(path, sep="\t", comment="#", dtype=str)

df

,Splicing Factor,Gene,Aliases,GeneID,HomoloGene,Uniprot,Binding Domain(s),MIM,Protein Interactors,Chemical Interactors,Expression,CLIP,Unnamed: 12
0,9G8,SFRS7,"splicing factor arginine/serine-rich 7 35kDa, ...",6432,http://www.ncbi.nlm.nih.gov/gene?Db=homologene...,Q16629,1 RRM (RNA recognition motif) domain; 1 CCHC-t...,NaN,"CDK6, ESR1, GABARAP, GABARAPL1, GABARAPL2, HDG...",NaN,http://cgap.nci.nih.gov/Genes/GeneInfo?ORG=Hs&...,NaN,NaN
1,CUG-BP1,CUGBP1,"CUG triplet repeat RNA binding protein 1, CUGB...",10658,http://www.ncbi.nlm.nih.gov/gene?Db=homologene...,Q92879,3 RRM (RNA recognition motif) domains,Myotonic distrophy (DM) [MIM:160900],"FUBP1, PPBP, TOM1L1, USP10 (IntAct Database); ...",NaN,http://cgap.nci.nih.gov/Genes/GeneInfo?ORG=Hs&...,NaN,NaN
2,DAZAP1,DAZAP1,DAZ associated protein 1,26528,http://www.ncbi.nlm.nih.gov/gene?Db=homologene...,Q96EP5,2 RRM (RNA recognition motif) domains,NaN,"GABARAP, GABARAPL1, GABARAPL2, MAP1LC3A, MAP1L...",NaN,http://cgap.nci.nih.gov/Genes/GeneInfo?ORG=Hs&...,NaN,NaN
3,ETR-3,CUGBP2,"CUG triplet repeat RNA binding protein 2, NAPO...",10659,http://www.ncbi.nlm.nih.gov/gene?Db=homologene...,O95319,3 RRM (RNA recognition motif) domains,NaN,PCBP1 (IntAct Database); PCBP1 (MINT Database)...,NaN,http://cgap.nci.nih.gov/Genes/GeneInfo?ORG=Hs&...,NaN,NaN
4,FMRP,FMR1,"fragile X mental retardation 1, POF, POF1, FRA...",2332,http://www.ncbi.nlm.nih.gov/gene?Db=homologene...,Q06787,2 KH domains,Fragile X syndrome [MIM:300624]. Fragile X tre...,"CYFIP1, CYFIP2, ESR1, ESR2, PRKAA1, STAU1 (Int...",NaN,http://cgap.nci.nih.gov/Genes/GeneInfo?ORG=Hs&...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,QKI,QKI,"QKI KH domain containing RNA binding, QK, Hqk,...",9444,http://www.ncbi.nlm.nih.gov/gene?Db=homologene...,Q96PU8,1 KH domain,NaN,"DEPP, FUBP3, HCLS1, HNRNPK, PCBP1, PCBP2, PCBP...",NaN,http://cgap.nci.nih.gov/Genes/GeneInfo?ORG=Hs&...,http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?...,NaN
67,hnRNP G,RBMX,"RNA binding motif protein X-linked, RNMX, HNRP...",27316,http://www.ncbi.nlm.nih.gov/gene?Db=homologene...,P38159,1 RRM (RNA recognition motif) domain,NaN,"CCDC33, CIRBP, CNBP, CSNK2A1, ESR1, FAM103A1, ...",NaN,http://cgap.nci.nih.gov/Genes/GeneInfo?ORG=Hs&...,NaN,NaN
68,SRm160,SRRM1,"serine/arginine repetitive matrix 1, POP101, S...",10250,http://www.ncbi.nlm.nih.gov/gene?Db=homologene...,Q8IYB3,1 PWI domain,NaN,"ABI1, ESR1, NXF1, RNPS1, SPOP, UPF1, UPF2, UPF...",NaN,http://cgap.nci.nih.gov/Genes/GeneInfo?ORG=Hs&...,NaN,NaN
69,ESRP1,ESRP1,"epithelial splicing regulatory protein 1, RBM3...",54845,http://www.ncbi.nlm.nih.gov/gene?Db=homologene...,Q6NXG1,3 RRM (RNA recognition motif) domains,NaN,UBC (BioGRID Database),NaN,http://cgap.nci.nih.gov/Genes/GeneInfo?ORG=Hs&...,NaN,NaN
70,ESRP2,ESRP2,"epithelial splicing regulatory protein 2, RBM3...",80004,http://www.ncbi.nlm.nih.gov/gene?Db=homologene...,Q9H6T0,3 RRM (RNA recognition motif) domains,NaN,NUMBL (IntAct Database),NaN,http://cgap.nci.nih.gov/Genes/GeneInfo?ORG=Hs&...,NaN,NaN

In [2]:
saf = df["Gene"].to_list()
saf

['SFRS7',
 'CUGBP1',
 'DAZAP1',
 'CUGBP2',
 'FMR1',
 'A2BP1',
 'RBFOX2',
 'HNRNPA0',
 'HNRNPA1',
 'HNRNPA2B1',
 'HNRNPC',
 'HNRNPC',
 'HNRNPC',
 'HNRNPD',
 'HNRNPD',
 'HNRPDL',
 'PCBP1',
 'PCBP2',
 'HNRNPF',
 'HNRNPH1',
 'HNRNPH2',
 'HNRNPH3',
 'PTBP1',
 'HNRNPK',
 'HNRNPK',
 'HNRNPL',
 'HNRPLL',
 'HNRNPM',
 'FUS',
 'HNRNPU',
 'TRA2A',
 'TRA2B',
 'ELAVL2',
 'ELAVL4',
 'ELAVL1',
 'KHSRP',
 'MBNL1',
 'NOVA1',
 'NOVA2',
 'PTBP2',
 'SFPQ',
 'RBM25',
 'RBM4',
 'KHDRBS1',
 'SF3B1',
 'SFRS2',
 'SF1',
 'SFRS1',
 'KHDRBS2',
 'KHDRBS3',
 'SFRS3',
 'SFRS9',
 'SFRS13A',
 'SFRS5',
 'SFRS11',
 'SFRS6',
 'SFRS4',
 'TARDBP',
 'TIA1',
 'TIAL1',
 'YBX1',
 'ZRANB2',
 'ELAVL3',
 'RBM5',
 'SYNCRIP',
 'HNRNPA3',
 'QKI',
 'RBMX',
 'SRRM1',
 'ESRP1',
 'ESRP2']

### SplicingLore

In [3]:
slpath = "/Users/zihengdai/Desktop/Thesis/data/SplicingLore/suppl_data/Table_S1_datasets.xlsx"

sheet_name = 'SF'

sl_sf = pd.read_excel(slpath, sheet_name=sheet_name)

sl_sf

   Splicing factor  Number of datasets
0           AKAP8L                   2
1              AQR                   1
2            CCAR1                   1
3            CELF1                   1
4           DAZAP1                   4
..             ...                 ...
70          TARDBP                   1
71            TIA1                   1
72         TRA2A_B                   2
73           U2AF1                   4
74           U2AF2                   4

[75 rows x 2 columns]

In [4]:
sl = sl_sf["Splicing factor"].to_list()
sl

['AKAP8L',
 'AQR',
 'CCAR1',
 'CELF1',
 'DAZAP1',
 'DDX5_DDX17',
 'ESRP2',
 'EWSR1',
 'FUBP1',
 'FUS',
 'GPKOW',
 'HNRNPA1',
 'HNRNPA2B1',
 'HNRNPC',
 'HNRNPD',
 'HNRNPF',
 'HNRNPH1',
 'HNRNPK',
 'HNRNPL',
 'HNRNPM',
 'HNRNPU',
 'KHSRP',
 'MATR3',
 'MBNL1',
 'MBNL1_2',
 'MBNL2',
 'NCBP2',
 'PCBP1',
 'PCBP2',
 'PPIG',
 'PPP1R8',
 'PRPF4',
 'PRPF8',
 'PTBP1',
 'PTBP1_2',
 'PUF60',
 'QKI',
 'RAVER1',
 'RBFOX2',
 'RBM10',
 'RBM15',
 'RBM17',
 'RBM22',
 'RBM25',
 'RBM39',
 'RBM47',
 'RBMX',
 'SAFB2',
 'SART3',
 'SF1',
 'SF3A3',
 'SF3B1',
 'SF3B4',
 'SFPQ',
 'SMN1',
 'SMNDC1',
 'SNRNP200',
 'SNRNP70',
 'SNRPC',
 'SRSF1',
 'SRSF10',
 'SRSF2',
 'SRSF3',
 'SRSF5',
 'SRSF6',
 'SRSF7',
 'SRSF9',
 'STAU1',
 'SUGP2',
 'TAF15',
 'TARDBP',
 'TIA1',
 'TRA2A_B',
 'U2AF1',
 'U2AF2']

### KEGG_SPLICEOSOME

In [5]:
import json

file_name = '/Users/zihengdai/Desktop/Thesis/data/KEGG_SPLICEOSOME/KEGG_SPLICEOSOME.v2025.1.Hs.json'
with open(file_name, 'r') as f:
    data = json.load(f)
kegg_sf_list = data['KEGG_SPLICEOSOME']['geneSymbols']

ks = pd.Series(kegg_sf_list).to_list()

ks

['ACIN1',
 'ALYREF',
 'AQR',
 'BCAS2',
 'BUD31',
 'CCDC12',
 'CDC40',
 'CDC5L',
 'CHERP',
 'CRNKL1',
 'CTNNBL1',
 'CWC15',
 'DDX23',
 'DDX39B',
 'DDX42',
 'DDX46',
 'DDX5',
 'DHX15',
 'DHX16',
 'DHX38',
 'DHX8',
 'EFTUD2',
 'EIF4A3',
 'HNRNPA1',
 'HNRNPA1L2',
 'HNRNPA1P60',
 'HNRNPA3',
 'HNRNPC',
 'HNRNPK',
 'HNRNPM',
 'HNRNPU',
 'HSPA1A',
 'HSPA1B',
 'HSPA1L',
 'HSPA2',
 'HSPA6',
 'HSPA8',
 'ISY1',
 'LSM2',
 'LSM3',
 'LSM4',
 'LSM5',
 'LSM6',
 'LSM7',
 'LSM8',
 'MAGOH',
 'MAGOHB',
 'NCBP1',
 'NCBP2',
 'PCBP1',
 'PHF5A',
 'PLRG1',
 'PPIE',
 'PPIH',
 'PPIL1',
 'PQBP1',
 'PRPF18',
 'PRPF19',
 'PRPF3',
 'PRPF31',
 'PRPF38A',
 'PRPF38B',
 'PRPF4',
 'PRPF40A',
 'PRPF40B',
 'PRPF6',
 'PRPF8',
 'PUF60',
 'RBM17',
 'RBM22',
 'RBM25',
 'RBM8A',
 'RBMX',
 'SART1',
 'SF3A1',
 'SF3A2',
 'SF3A3',
 'SF3B1',
 'SF3B2',
 'SF3B3',
 'SF3B4',
 'SF3B5',
 'SF3B6',
 'SLU7',
 'SMNDC1',
 'SNRNP200',
 'SNRNP27',
 'SNRNP40',
 'SNRNP70',
 'SNRPA',
 'SNRPA1',
 'SNRPB',
 'SNRPB2',
 'SNRPC',
 'SNRPD1',
 'SNRPD2',
 'SNRPD3',
 'SNRPE',
 'SNRPF',
 'SNRPG',
 'SNU13',
 'SNW1',
 'SRSF1',
 'SRSF10',
 'SRSF2',
 'SRSF3',
 'SRSF4',
 'SRSF5',
 'SRSF6',
 'SRSF7',
 'SRSF8',
 'SRSF9',
 'SYF2',
 'TCERG1',
 'THOC1',
 'THOC2',
 'THOC3',
 'TRA2A',
 'TRA2B',
 'TXNL4A',
 'U2AF1',
 'U2AF2',
 'U2SURP',
 'USP39',
 'WBP11',
 'XAB2',
 'ZMAT2']

### ENCODE

In [6]:
en_raw = pd.read_excel('/Users/zihengdai/Desktop/Thesis/data/ENCODE/41586_2020_2077_MOESM3_ESM.xlsx', header=1)
en_raw

,Unnamed: 0,Unnamed: 1,Essential Genes,Splicing regulation,Spliceosome,RNA modification,3' end processing,rRNA processing,Ribosome & basic translation,RNA stability & decay,...,dRBM,PUM_HD,eCLIP HepG2,eCLIP K562,RNAseq HepG2,RNAseq K562,RBNS,Image HepG2,ChIPseq HepG2,ChIPseq K562
0,A1CF,ENSG00000148584,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1,AARS,ENSG00000090861,1,0,0,0,0,0,0,0,...,0,0,0,1,1,1,0,1,0,0
2,AATF,ENSG00000108270,1,0,0,0,0,0,0,0,...,0,0,0,1,1,1,0,1,0,0
3,ABCF1,ENSG00000204574,1,0,0,0,0,0,0,0,...,0,0,0,1,1,1,0,1,0,0
4,ABT1,ENSG00000146109,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,AGO2,ENSG00000123908,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
352,NIPBL,ENSG00000164190,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
353,ZNF800,ENSG00000048405,0,0,0,0,0,0,0,0,...,0,0,1,1,0,1,0,0,0,0
354,SDAD1,ENSG00000198301,1,0,0,0,0,0,0,0,...,0,0,1,1,1,1,0,0,0,0
355,STAU2,ENSG00000040341,0,0,0,0,0,0,0,1,...,1,0,1,0,0,0,0,0,0,0

In [7]:
old_name = en_raw.columns[0]
en_raw.rename(columns={old_name: 'RBP_Name'}, inplace=True)
en_filtered = en_raw[["RBP_Name", 'Splicing regulation', 'Spliceosome']].copy()
en_filtered

    RBP_Name  Splicing regulation  Spliceosome
0       A1CF                    0            0
1       AARS                    0            0
2       AATF                    0            0
3      ABCF1                    0            0
4       ABT1                    0            0
..       ...                  ...          ...
351     AGO2                    1            0
352    NIPBL                    0            0
353   ZNF800                    0            0
354    SDAD1                    0            0
355    STAU2                    0            0

[356 rows x 3 columns]

In [8]:
en_sf = en_filtered[
    (en_filtered['Splicing regulation'].fillna(0) == 1) |
    (en_filtered['Spliceosome'].fillna(0) == 1)
]

en = en_sf['RBP_Name'].to_list()
en

['ADAR',
 'AKAP8L',
 'AQR',
 'BUD13',
 'CCAR1',
 'CCAR2',
 'CCNL1',
 'CDC40',
 'CELF1',
 'DAZAP1',
 'DDX20',
 'DDX42',
 'DDX5',
 'EFTUD2',
 'ESRP1',
 'EWSR1',
 'FMR1',
 'FUBP1',
 'FUS',
 'GEMIN5',
 'GPKOW',
 'HNRNPA1',
 'HNRNPA2B1',
 'HNRNPC',
 'HNRNPD',
 'HNRNPF',
 'HNRNPH1',
 'HNRNPH2',
 'HNRNPK',
 'HNRNPL',
 'HNRNPLL',
 'HNRNPM',
 'HNRNPU',
 'KHDRBS1',
 'KHDRBS2',
 'KHDRBS3',
 'KHSRP',
 'LSM4',
 'MATR3',
 'MBNL1',
 'MSI1',
 'NCBP2',
 'NONO',
 'NOVA1',
 'PCBP1',
 'PCBP2',
 'PCBP3',
 'PNN',
 'PPIG',
 'PPP1R8',
 'PRPF4',
 'PRPF6',
 'PRPF8',
 'PSIP1',
 'PTBP1',
 'PTBP3',
 'PUF60',
 'QKI',
 'RAVER1',
 'RBFOX2',
 'RBFOX3',
 'RBM14',
 'RBM15',
 'RBM15B',
 'RBM17',
 'RBM22',
 'RBM23',
 'RBM24',
 'RBM25',
 'RBM39',
 'RBM4',
 'RBM47',
 'RBM5',
 'RBM6',
 'SART3',
 'SF1',
 'SF3A3',
 'SF3B1',
 'SF3B4',
 'SFPQ',
 'SMN1',
 'SMNDC1',
 'SND1',
 'SNRNP200',
 'SNRNP70',
 'SNRPA',
 'SRSF1',
 'SRSF10',
 'SRSF11',
 'SRSF2',
 'SRSF3',
 'SRSF4',
 'SRSF5',
 'SRSF7',
 'SRSF8',
 'SRSF9',
 'STAU1',
 'SUGP2',
 'SYNCRIP',
 'TARDBP',
 'TFIP11',
 'TIA1',
 'TIAL1',
 'TRA2A',
 'U2AF1',
 'U2AF2',
 'ZCRB1',
 'ZNF326',
 'ZRANB2',
 'SAFB',
 'AGO2']

### Union of all unique SFs

In [9]:
saf_set = set(saf)
sl_set = set(sl)
ks_set = set(ks)
en_set = set(en)

comprehensive_sfs_set = saf_set.union(sl_set, ks_set, en_set)
comprehensive_sfs = sorted(list(comprehensive_sfs_set))
comprehensive_sfs

['A2BP1',
 'ACIN1',
 'ADAR',
 'AGO2',
 'AKAP8L',
 'ALYREF',
 'AQR',
 'BCAS2',
 'BUD13',
 'BUD31',
 'CCAR1',
 'CCAR2',
 'CCDC12',
 'CCNL1',
 'CDC40',
 'CDC5L',
 'CELF1',
 'CHERP',
 'CRNKL1',
 'CTNNBL1',
 'CUGBP1',
 'CUGBP2',
 'CWC15',
 'DAZAP1',
 'DDX20',
 'DDX23',
 'DDX39B',
 'DDX42',
 'DDX46',
 'DDX5',
 'DDX5_DDX17',
 'DHX15',
 'DHX16',
 'DHX38',
 'DHX8',
 'EFTUD2',
 'EIF4A3',
 'ELAVL1',
 'ELAVL2',
 'ELAVL3',
 'ELAVL4',
 'ESRP1',
 'ESRP2',
 'EWSR1',
 'FMR1',
 'FUBP1',
 'FUS',
 'GEMIN5',
 'GPKOW',
 'HNRNPA0',
 'HNRNPA1',
 'HNRNPA1L2',
 'HNRNPA1P60',
 'HNRNPA2B1',
 'HNRNPA3',
 'HNRNPC',
 'HNRNPD',
 'HNRNPF',
 'HNRNPH1',
 'HNRNPH2',
 'HNRNPH3',
 'HNRNPK',
 'HNRNPL',
 'HNRNPLL',
 'HNRNPM',
 'HNRNPU',
 'HNRPDL',
 'HNRPLL',
 'HSPA1A',
 'HSPA1B',
 'HSPA1L',
 'HSPA2',
 'HSPA6',
 'HSPA8',
 'ISY1',
 'KHDRBS1',
 'KHDRBS2',
 'KHDRBS3',
 'KHSRP',
 'LSM2',
 'LSM3',
 'LSM4',
 'LSM5',
 'LSM6',
 'LSM7',
 'LSM8',
 'MAGOH',
 'MAGOHB',
 'MATR3',
 'MBNL1',
 'MBNL1_2',
 'MBNL2',
 'MSI1',
 'NCBP1',
 'NCBP2',
 'NONO',
 'NOVA1',
 'NOVA2',
 'PCBP1',
 'PCBP2',
 'PCBP3',
 'PHF5A',
 'PLRG1',
 'PNN',
 'PPIE',
 'PPIG',
 'PPIH',
 'PPIL1',
 'PPP1R8',
 'PQBP1',
 'PRPF18',
 'PRPF19',
 'PRPF3',
 'PRPF31',
 'PRPF38A',
 'PRPF38B',
 'PRPF4',
 'PRPF40A',
 'PRPF40B',
 'PRPF6',
 'PRPF8',
 'PSIP1',
 'PTBP1',
 'PTBP1_2',
 'PTBP2',
 'PTBP3',
 'PUF60',
 'QKI',
 'RAVER1',
 'RBFOX2',
 'RBFOX3',
 'RBM10',
 'RBM14',
 'RBM15',
 'RBM15B',
 'RBM17',
 'RBM22',
 'RBM23',
 'RBM24',
 'RBM25',
 'RBM39',
 'RBM4',
 'RBM47',
 'RBM5',
 'RBM6',
 'RBM8A',
 'RBMX',
 'SAFB',
 'SAFB2',
 'SART1',
 'SART3',
 'SF1',
 'SF3A1',
 'SF3A2',
 'SF3A3',
 'SF3B1',
 'SF3B2',
 'SF3B3',
 'SF3B4',
 'SF3B5',
 'SF3B6',
 'SFPQ',
 'SFRS1',
 'SFRS11',
 'SFRS13A',
 'SFRS2',
 'SFRS3',
 'SFRS4',
 'SFRS5',
 'SFRS6',
 'SFRS7',
 'SFRS9',
 'SLU7',
 'SMN1',
 'SMNDC1',
 'SND1',
 'SNRNP200',
 'SNRNP27',
 'SNRNP40',
 'SNRNP70',
 'SNRPA',
 'SNRPA1',
 'SNRPB',
 'SNRPB2',
 'SNRPC',
 'SNRPD1',
 'SNRPD2',
 'SNRPD3',
 'SNRPE',
 'SNRPF',
 'SNRPG',
 'SNU13',
 'SNW1',
 'SRRM1',
 'SRSF1',
 'SRSF10',
 'SRSF11',
 'SRSF2',
 'SRSF3',
 'SRSF4',
 'SRSF5',
 'SRSF6',
 'SRSF7',
 'SRSF8',
 'SRSF9',
 'STAU1',
 'SUGP2',
 'SYF2',
 'SYNCRIP',
 'TAF15',
 'TARDBP',
 'TCERG1',
 'TFIP11',
 'THOC1',
 'THOC2',
 'THOC3',
 'TIA1',
 'TIAL1',
 'TRA2A',
 'TRA2A_B',
 'TRA2B',
 'TXNL4A',
 'U2AF1',
 'U2AF2',
 'U2SURP',
 'USP39',
 'WBP11',
 'XAB2',
 'YBX1',
 'ZCRB1',
 'ZMAT2',
 'ZNF326',
 'ZRANB2']

In [10]:
len(comprehensive_sfs)

233

In [24]:
pd.DataFrame(comprehensive_sfs).to_csv("comprehensive_sfs.csv", index=False, header=False)

In [11]:
final_df = pd.DataFrame(list(comprehensive_sfs), columns=['Splicing_Factor'])
final_df = final_df.sort_values('Splicing_Factor').reset_index(drop=True)

final_df['In_SplicingLore'] = final_df['Splicing_Factor'].isin(sl_set)
final_df['In_SpliceAidF'] = final_df['Splicing_Factor'].isin(saf_set)
final_df['In_KEGG'] = final_df['Splicing_Factor'].isin(ks_set)
final_df['In_ENCODE'] = final_df['Splicing_Factor'].isin(en_set)

In [12]:
annotation_columns = ['In_SplicingLore', 'In_SpliceAidF', 'In_KEGG', 'In_ENCODE']
final_df['Source_Count'] = final_df[annotation_columns].sum(axis=1)

overlap_counts = final_df['Source_Count'].value_counts().sort_index(ascending=False)

high_confidence_sfs = final_df[final_df['Source_Count'] == 4]['Splicing_Factor'].tolist()

In [13]:
print("Present of all unique SFs in each source:")
final_df

Present of all unique SFs in each source:

,Splicing_Factor,In_SplicingLore,In_SpliceAidF,In_KEGG,In_ENCODE,Source_Count
0,A2BP1,False,True,False,False,1
1,ACIN1,False,False,True,False,1
2,ADAR,False,False,False,True,1
3,AGO2,False,False,False,True,1
4,AKAP8L,True,False,False,True,2
...,...,...,...,...,...,...
228,YBX1,False,True,False,False,1
229,ZCRB1,False,False,False,True,1
230,ZMAT2,False,False,True,False,1
231,ZNF326,False,False,False,True,1
232,ZRANB2,False,True,False,True,2

In [14]:
print("Analysis of Splicing Factor Overlap")
print(f"Total unique SFs: {len(final_df)}\n")
print("Number of SFs by source count:")
print(overlap_counts)

print(f"\nHighest-Confidence SFs (found in all 4 sources): {len(high_confidence_sfs)}")
print(high_confidence_sfs)

Analysis of Splicing Factor Overlap
Total unique SFs: 233

Number of SFs by source count:
Source_Count
4      8
3     40
2     43
1    142
Name: count, dtype: int64

Highest-Confidence SFs (found in all 4 sources): 8
['HNRNPA1', 'HNRNPC', 'HNRNPK', 'HNRNPM', 'HNRNPU', 'PCBP1', 'RBM25', 'SF3B1']